### PR TITLE
added materialize

### PR DESCRIPTION
**Pull request by aeolyus**
Font looks nicer plus the signup form is slightly better.

TODO: add CSS (without breaking it again)

### CODE REVIEW

**Comment by varmichelle** [comment]
radio buttons don't work
image

**Comment by varmichelle** [comment]
input space lines overlap with side navbar
image

**Comment by aeolyus** [comment]
These issues are inherent. No css was added, just the materialize meteor package. Hence, the todo

**Comment by varmichelle** [comment]
the radio button should be fixed first though because it's necessary when we're testing things involving tournaments or signup stuff (I think we had this issue in the other repo, and it was resolved)

**Comment by aeolyus** [comment]
It shouldn't be difficult to resolve.

**Pull request closed without merging**
